version: "3.8"

volumes:
  postgres_data: { }

services:
  postgres:
    image: docker.io/bitnami/postgresql:14
    ports:
      - "5432:5432"
    volumes:
      - 'postgres_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=denishoang
      - POSTGRESQL_DATABASE=products
      - POSTGRESQL_PASSWORD=pgpassword
